international_time_homepage:
    path:     /
    defaults: { _controller: InternationalTimeBundle:Default:index }

international_time_get_clock_data_by_ajax:
    path:     /get_clock_data
    defaults: { _controller: InternationalTimeBundle:Default:getClockDataByAjax }
